name: stroke_dti
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.11.4
  - ipykernel
  - pandas
  - statannotations
  - seaborn
  - plotly
  - pip
  - setuptools
  - pip:
      - torch==2.5.1
      - -e . # Install your package in editable mode
      - ./modified_packages/keggx # Path to the modified package
